Feature
daohoangbk/todoslist pull request #6
Opened 2017-08-08 07:43 UTC by daohoangbk

Use single quote

2017-08-08 07:44 UTC, hungkm1412 approved these changes
LGTM 👍

2017-08-09 15:28 UTC, saphira177 requested changes

2017-08-09 15:28 UTC, banhbaochay commented on src/components/FormAddItem.vue
> +    <div class="formadditem form-inline">
css class name should be hyphen separated. Ex: form-add-item instead of formadditem

2017-08-09 15:28 UTC, banhbaochay commented on src/components/FormAddItem.vue
> +          <option v-for="(user, index) in listUsers" :value="user.id">{{user.name}}</option>
Why do we need index here?

2017-08-09 15:28 UTC, banhbaochay commented on src/components/FormAddUser.vue
> +  <div class="formadduser">
css class name should be hyphen separated

2017-08-09 15:28 UTC, banhbaochay commented on src/components/FormAddUser.vue
> +            deleted: false
Should add comma at the end of object attribute. See javascript convention for more details

2017-08-09 15:28 UTC, banhbaochay commented on src/components/FormAddUser.vue
> +<style>
Should not place css here

2017-08-09 15:28 UTC, banhbaochay commented on src/components/ListItem.vue
> +<style>
Should not place css here

2017-08-09 15:28 UTC, banhbaochay commented on src/components/ListUser.vue
> +.form-horizontal .form-group {
Should not place css here

2017-08-10 02:07 UTC, daohoangbk commented on src/components/FormAddUser.vue
> +  <div class="formadduser">
thank you! i will edit it.

2017-08-10 02:25 UTC, daohoangbk commented on src/components/FormAddItem.vue
> +          <option v-for="(user, index) in listUsers" :value="user.id">{{user.name}}</option>
Yeah. It is redundant, i will remove it.

2017-08-10 02:28 UTC, daohoangbk commented on src/components/FormAddUser.vue
> +            deleted: false
It rights, but when i comma after the end object attribute, the eslint show 1 error requiring remove it.

2017-08-10 02:31 UTC, daohoangbk commented on src/components/FormAddUser.vue
> +<style>
Where should i place css?

2017-08-10 02:53 UTC, banhbaochay commented on src/components/FormAddUser.vue
> +<style>
In css file

2017-08-10 03:19 UTC, banhbaochay commented on src/components/FormAddUser.vue
> +            deleted: false
Ok, so please ignore this point

2017-08-10 03:29 UTC, daohoangbk commented on src/components/FormAddUser.vue
> +<style>
thank you, i did it.

2017-08-11 08:11 UTC, saphira177 requested changes

2017-08-11 08:11 UTC, banhbaochay commented on src/components/ListItem.vue
> +              case 'all': return true
Should not combine return and switch. You can use a variable with switch, then return based on variable value

2017-08-11 08:11 UTC, banhbaochay commented on src/components/ListItem.vue
> +        let list = this.todosList.slice()
Try to avoid return in multiple if. Need to refactor this method

2017-08-11 10:10 UTC, merged